export const limitedUses = [
    {   
        id: 1,
        level: 1,
        name: "Darkside",
        maxUses: 5,
        type: "ability",
        description: "Deal an additional 1d6 of damage per attack.",
        shortRestRecover: false 
    },
    {   
        id: 2,
        level: 3,
        name: "Hellish Rebuke",
        maxUses: 1,
        type: "spell",
        spellLevel: 2,
        description: "... (Cast hellish rebuke as a 2nd level spell)",
        shortRestRecover: false,
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff"
    },
    {   
        id: 3,
        level: 5,
        name: "Darkness",
        maxUses: 1,
        type: "spell",
        description: "...",
        shortRestRecover: false,
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff"
    },
    {   
        id: 4,
        level: 6,
        name: "Dark Nebula",
        maxUses: 5,
        type: "ability",
        description: "Sacrifice a hit die to cast dark nebula on a 30ft cone. All creatures hit make a dexterity saving throw, taking half the damage of a successful save. Damage to self is 2d4, enemies take 4d6 necrotic damage.",
        shortRestRecover: false 
    },
    {   
        id: 5,
        level: 9,
        name: "Detect Evil and Good",
        maxUses: 0,
        type: "spell",
        description: "...",
        shortRestRecover: false,
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff"
    },
    {   
        id: 6,
        level: 10,
        name: "Soul Survivor",
        maxUses: 1,
        type: "ability",
        description: "As a bonus action, choose a target to cast soul survivor on. If target before your next turn, recover one hit die.",
        shortRestRecover: true 
    },
    {   
        id: 7,
        level: 11,
        name: "Speak with Death",
        maxUses: 2,
        type: "spell",
        description: "...",
        shortRestRecover: false,
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff"
    },
    {   
        id: 8,
        level: 11,
        name: "Tongues",
        maxUses: 2,
        type: "spell",
        description: "...",
        shortRestRecover: false,
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff"
    },
    {   
        id: 9,
        level: 13,
        name: "Mired Empathy",
        maxUses: 5,
        type: "ability",
        description: "...",
        shortRestRecover: false 
    },
    {   
        id: 10,
        level: 14,
        name: "Dirty Fighter",
        maxUses: 33,
        type: "ability",
        description: "Deal an additional 1d6 of damage per attack.",
        shortRestRecover: false 
    },
    {   
        id: 11,
        level: 18,
        name: "Circle of Darkness",
        maxUses: 0,
        type: "spell",
        description: "... Expend a hit die to cast circle of death. ",
        shortRestRecover: false,
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff"
    }
];