export const limitedUses = [
    {   
        id: 1,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.",
        shortRestRecover: true 
    },
    {   
        id: 2,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.",
        shortRestRecover: true
    },
    {   
        id: 3,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    },
    {   
        id: 4,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    },
    {   
        id: 5,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    },
    {   
        id: 6,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    },
    {   
        id: 7,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    },
    {   
        id: 8,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    },
    {   
        id: 9,
        name: "Divine Sense",
        maxUses: 15,
        type: "spell",
        level: "cantrip", 
        castingTime: "1 Action", 
        rangeAndArea: "Touch", 
        duration: "1 minute", 
        school: "Divination", 
        attackAndSave: "None", 
        damageAndEffect: "Buff", 
        description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends." ,
        shortRestRecover: false
    }
];